// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlITHvjMBYgladTcKvkMsTkssTrgJ5NI',
    appId: '1:368853424383:web:c233cf4b184a84d945d4ca',
    messagingSenderId: '368853424383',
    projectId: 'car-rental-app-2004',
    authDomain: 'car-rental-app-2004.firebaseapp.com',
    storageBucket: 'car-rental-app-2004.firebasestorage.app',
    measurementId: 'G-SQ1V2PR3S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAQWG3sBI94omA9OWjisOCeXr5VX7SCg',
    appId: '1:368853424383:android:7de16ddd9f436cc845d4ca',
    messagingSenderId: '368853424383',
    projectId: 'car-rental-app-2004',
    storageBucket: 'car-rental-app-2004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnIXtzhTOnzlHyax88kkoH_3LCBjpD21M',
    appId: '1:368853424383:ios:38c5c872f251fcb545d4ca',
    messagingSenderId: '368853424383',
    projectId: 'car-rental-app-2004',
    storageBucket: 'car-rental-app-2004.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnIXtzhTOnzlHyax88kkoH_3LCBjpD21M',
    appId: '1:368853424383:ios:38c5c872f251fcb545d4ca',
    messagingSenderId: '368853424383',
    projectId: 'car-rental-app-2004',
    storageBucket: 'car-rental-app-2004.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAlITHvjMBYgladTcKvkMsTkssTrgJ5NI',
    appId: '1:368853424383:web:5b175f6431caa04e45d4ca',
    messagingSenderId: '368853424383',
    projectId: 'car-rental-app-2004',
    authDomain: 'car-rental-app-2004.firebaseapp.com',
    storageBucket: 'car-rental-app-2004.firebasestorage.app',
    measurementId: 'G-3YDZ9BMM7M',
  );
}
